baseURL = "https://tjoosep.github.io/"
languageCode = "en-us"
title = "The simple engineer blog"
theme = "hugo-notepadium"
paginate = 10
summaryLength = 50

[markup.highlight]
codeFences = true
noClasses = true
style = "github"

[params]
style = "light"

[params.syntax]
use = "none"
theme = "intellij"

[params.nav]
showCategories = true
showTags = true	


# custom navigation items

[[params.nav.custom]]
title = "About"
url = "/about"
