baseURL = "https://tjoosep.github.io/"
languageCode = "en-us"
title = "Just blog"
theme = "hugo-notepadium"
paginate = 10
summaryLength = 50
math = true

[permalinks]
posts = "/posts/"

[markup.highlight]
codeFences = true
noClasses = true
style = "github"

[params]
style = "light"

[params.syntax]
use = "none"
theme = "intellij"

[params.nav]
showCategories = false
showTags = true	

# custom navigation items
[[params.nav.custom]]
title = "Posts"
url = "/posts"

[[params.nav.custom]]
title = "Data structures"
url = "/ds"

[[params.nav.custom]]
title = "OOP"
url = "/oop"

[[params.nav.custom]]
title = "SOLID"
url = "/solid"

[[params.nav.custom]]
title = "Algorithms"
url = "/algorithms"

[[params.nav.custom]]
title = "Design patterns"
url = "/patterns"

[[params.nav.custom]]
title = "Hash table"
url = "/hash-table"

[[params.nav.custom]]
title = "Graphs"
url = "/graphs"


[[params.nav.custom]]
title = "Trees"
url = "/trees"